name = "xclash-vs-planner"
main = "src/index.ts"
compatibility_date = "2026-06-18"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "xclash-vs-planner-db"
database_id = "ac455dfd-9dc8-4d6d-b79b-20d05c8a2127"
